### PR TITLE
Creation of a README file, and team.html

### PR DESCRIPTION
**Pull request by ProphetDaniel**

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@ProphetDaniel thanks for putting  README.md together.

Can you add some text at the beginning that explains the purpose of this repo (i.e. it is the code behind the interledger.org website)?

I'm not sure what the purpose of the team.html page is? It doesn't appear to fit in with the style of the other pages either.

**Comment by ProphetDaniel** [comment]
I added the introductory information as you pointed out to README.md. I hope that is what you are looking for. Regarding the team.html page the idea is to create a team page to be linked to the main page interledger team section. As I understand it is not ready yet and style changes are probably needed I created a draft team.html that is not yet linked in the main page. As soon it is approved we can then update the main page.

**Comment by adrianhopebailie** [comment]
> I added the introductory information as you pointed out to README.md. I hope that is what you are looking for.

Not really 😄 

This repo holds the code behind the website at https://interledger.org. The README should state that. I see why you might want to explain what the project is but not sure why you'd want stuff from the actual website in the README?

> Regarding the team.html page the idea is to create a team page to be linked to the main page interledger team section. As I understand it is not ready yet and style changes are probably needed I created a draft team.html that is not yet linked in the main page. As soon it is approved we can then update the main page. 

What do you mean by that? It looks like what you've built is using the look and feel from the W3C website not https://interledger.org. If you want to contribute a new page use one of the existing pages as a template and start with that.

**Comment by ProphetDaniel** [comment]
@adrianhopebailie, I made the README way more simple just to fulfill your requirement. And I also removed the team.html for now. Let me know your toughts...

**Pull request merged**
